name = "proplumbing"
main = "worker.js"
compatibility_date = "2024-12-01"
workers_dev = false

[assets]
directory = "./artifacts/plumbing-app/dist/public"
not_found_handling = "single-page-application"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "proflowplumbing-db"
database_id = "09e30cb1-2e25-4996-803a-d2c8a93444d6"

[[r2_buckets]]
binding = "R2"
bucket_name = "proflowplumbing-uploads"

[[routes]]
pattern = "proplumbing.techsavvyhawaii.com"
zone_name = "techsavvyhawaii.com"
custom_domain = true
